### PR TITLE
Sentence bar additions in locked screens & Localization basic work

### PR DESCRIPTION
**Pull request by Rukmini-Meda**
#### Features added

- Now, the text in the sentence bar can be added by just tapping on it.
- User can add some text, check its TTS and expand into a bigger view
- In the bigger view, the user can add large amounts of text and when input is done, it will be created as a tile in the sentence bar

#### Questions

- I haven't completely understood what is the screen that should be linked to the bookmark icon. It is mentioned in the design that it should save the TTS by opening a screen for adding a tile with that TTS. If I get some clarity on this, I can finish this.

#### Note

- I wrote the code by taking Jill's code as the main point, so I copied those files in this branch as I checked out this branch from the Summer2021 branch.

### CODE REVIEW

**Comment by Rukmini-Meda** [comment]
I fixed the merge conflicts and had to make small changes to resolve errors. I verified my part after resolving the conflicts and it seems to work fine. But, I definitely think the functionality done by Jill has to be verified if it's working fine after fixing the conflicts. I will look into it and verify that as well. But it will be assuring if @nganphan123 or @tungtrn once run it on their side and let me know if it's working fine. Then I can squash the commits and it will be ready to be merged.

**Comment by Rukmini-Meda** [comment]
As discussed in today's meeting, I've some small changes to make. I will tag once they're done.

**Review by tungtrn — APPROVED** [review]
Hey Rukmini,

Thank you for implementing the UI and the functionalities. It appears to work well on my end, I can add tile and text on the sentence bar.

I notice the "Add Tile" tile currently not allowing users to add the text tile onto the sentence bar and letting the user edit it. However, I think we can do it later.

For the UI, the navigation bar is a bit tight on my side so you may want to check the size (Screenshot below).
Screen Shot 2021-09-27 at 11 06 46 AM


Other than that, I think it is good to go. I am approving it now so you work on the API integration. Please also note down what part is done and what part is skipped for the MVP.

Thank you so much 👏👏

**Comment by nganphan123** [comment]
@tungtrn I think "Add tile" tile only works in unlocked mode

**Review by nganphan123 — CHANGES_REQUESTED** [review]
Good jobs @Rukmini-Meda. All the functions work well for me. However, there is an overflow when I use a smaller phone like this

overflow

@tungtrn  I have another question: if the user wants to listen  to the whole sentence. How can they do that ?

**Comment by tungtrn** [comment]
@nganphan123 @Rukmini-Meda Jill is right, I forgot to change the review after discussing it with Mr. BP. The Add tile only works in the unlocked mode so we may not need it for the locked mode. 
Based on what we have on the web now, users can click on white space on the sentence bar to hear the whole sentence

**Review by tungtrn — APPROVED** [review]

**Pull request merged**
