### PR TITLE
Jill/locked screens

### PR DESCRIPTION
**Pull request by tungtrn**

### CODE REVIEW

**Review by nganphan123 — COMMENTED** [review]
Nothing to change

**Review by tungtrn — COMMENTED** [review]
Great job @nganphan123 👏👏!!!

Most of the UI and the provider, state changes work on my end.

I just have a few minor details to add-in:
- I find the Background color change for the tile works perfectly fine but the text color change does not change the color of the label.
- Also in the Folder color change, I don't see the color of the folder changes after clicking on another color. Did you not work on it yet or we are skipping that in the MVP?
- In this image, I think the bar and the white sheet below it overlap each other. Do you think you resize them a bit so it appears nicer?
Screen Shot 2021-08-30 at 12 44 14 AM

If you have details to add on, please let me know. Thank you so much!!!

**Comment by nganphan123** [comment]
Thanks. I did the first 2 bullets.

**Comment by tungtrn** [comment]
@nganphan123 
Thank you so much for working on the first two bullets! The second bullet fix looks good and it works well on my end 👍

There is a small error on the first bullet fix. It changes the color of the text below the bar but when I click out onto the upper bar, it is still in the original color (Screenshot attached below). Maybe because you changed the temporary variable but not the one the put on the bar?

Other than that, the two fixes are good to go. Let me know when you work on the third bullet.

Thank you so much!! 

Screen Shot 2021-09-18 at 11 35 29 AM

**Comment by nganphan123** [comment]
@tungtrn thanks for reviewing. Everything should be fixed now. I also added the json code to load default boards. This should be generic for all api request files too.

**Pull request merged**
